# Location of BactQuerya_processing repository relative to the Snakefile
BactQuerya_location: .

# multiprocessing option
n_cpu: 3

# options for entrez_extract -a assembly-stats
entrez_extract:
  accession_file: test/test_accessions.txt
  email: empty
  assembly: assembly-stats
  gff: annotation
  genome: genome

# options for isolate_attributes
isolate_attributes:
  index_no: 0

# options for feature_extract
feature_extract:
  index_no: 0

# options for index_isolate_attributes
index_isolate_attributes:
  index: python_isolate_index