# Location of BactQuerya_processing repository relative to the Snakefile
BactQuerya_location: .

# multiprocessing option
n_cpu: 3

# options for extract_entrez_information
extract_entrez_information:
  accession_file: test/single.txt
  email: empty
  assembly: assembly-stats
  gff: annotation
  genome: genome

# options for single_meryl_dbs
single_meryl_dbs:
  single_files: meryl_single_files
  assembly_txt_file: meryl_single_files/assembly_str.txt

# options for merge_single_meryl_dbs
merge_single_meryl_dbs:
  merged_db_folder: meryl_merged_files

# options for run_merqury
run_merqury:
  merqury_output: merqury_output

# options for isolate_attributes
isolate_attributes:
  index_no: 0

# options for feature_extract
feature_extract:
  index_no: 0

# options for index_isolate_attributes
index_isolate_attributes:
  index: python_isolate_index3

# options for index_gene_features
index_gene_features:
  kmer_length: 31
