# Location of BacQuerya_processing repository relative to the Snakefile
BacQuerya_location: .

# whether this run is building the reference information for a species ("reference") or processing new isolates ("query")
# unless you are adding a new species to the indices, this has to be "query"
run_type: reference
skip_NCBI: False
skip_ENA: True
skip_genes: False

# needed for a "reference" run. Tells snakemake to add gene information merged together from all runs to the elastic gene index
index_genes: False
index_sequences: False #construct COBS index for genes
index_isolates: False

# whether we are indexing the GPS data or not
GPS: False

# whether we are indexing the ESC data or not
ESC: False

# name of GPS/ESC metadata json
supplementaryMetadataJSON: ESC_metadata.json

# multiprocessing option
n_cpu: 8

# options for extract_entrez_information
extract_entrez_information:
  accession_file: NCBI_requested_accessions.txt
  email: empty
  assembly: assembly-stats
  gff: annotation
  genome: genome

# options to extract sequence reads
extract_read_metadata:
  accession_file:  ESC_ENA_Accessions.txt

# options for single_meryl_dbs
single_meryl_dbs:
  single_files: meryl_single_files
  assembly_txt_file: meryl_single_files/assembly_str.txt

# options for merge_single_meryl_dbs
merge_single_meryl_dbs:
  merged_db_folder: meryl_merged_files

# options for run_merqury
run_merqury:
  merqury_output: merqury_output

# options for extract_assembly_stats
extract_assembly_stats:
  index_file: index_values.json

# options for index_isolate_attributes
index_isolate_attributes:
  index: isolate_index

# options for index_gene_features
index_sequences:
  kmer_length: 31
  gene_type: gene
  elasticSearchIndex: gene_index
  assembly_type: assembly
