name: BQ_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - numpy
  - biopython
  - bcbio-gff
  - joblib
  - tqdm
  - flask
  - flask-cors
  - tqdm
  - elasticsearch
  - cobs-index
  - merqury
  - meryl
  - pp-sketchlib
  - assembly_stats #https://github.com/MikeTrizna/assembly_stats